### ISSUE TITLE
Artifacts using TemporalMedian

### ISSUE THREAD

**Issue by Selur** [adworacz/zsmooth#1]
Am I missing something?
Using:
```
clip = core.lsmas.LWLibavSource(source="C:/Users/Selur/Desktop/test edge bars.avi", format="YUV422P8", stream_index=0, cache=0, prefer_hw=0)
clip = core.zsmooth.TemporalMedian(clip, radius=1`)
```
![grafik](https://github.com/adworacz/zsmooth/assets/843640/f0badb42-c642-488c-9f2f-2127d4dff54c)
![grafik](https://github.com/adworacz/zsmooth/assets/843640/ffa9e420-6f81-47dd-90c8-7d9384a38532)
![grafik](https://github.com/adworacz/zsmooth/assets/843640/d15964cb-8eb2-4c23-b11b-96af47d112e9)
with both the avx2 and the avx512 version on Windows11, Ryzen 9 7950X, Vapoursynth R65.
Artifacts change depending on the input color space.
This only happens with some files.

This does not happen with all files, but a bunch, I attached a small sample file
[example.zip](https://github.com/adworacz/zsmooth/files/15112824/example.zip)
![grafik](https://github.com/adworacz/zsmooth/assets/843640/b106c65d-df2a-4928-97c6-33d4164e9c7b)
no clue what the cause happens with different files with different resolution and color spaces.

**Comment by adworacz** [comment]
Fascinating - thanks for the bug report. I'll take a look at what could be causing this in the next few days.

Do the artifacts appear on any other filters, or just TemporalMedian?

**Comment by adworacz** [comment]
I have a sneaking suspicion that I already know what the issue is (and that's my handling of `stride`). I'll try and get some tests in soon.

**Comment by adworacz** [comment]
Solid, thank you for confirming @dnjulek . 

I'll update all of my functions to respect `stride` properly and then I'll post a new version.

**Comment by Selur** [comment]
Nice, looking forward to a fixed version.
(happy that it isn't an issue only I have and it is a problem with my hardware ;))

**Comment by adworacz** [comment]
Selur, please try the 0.3 release, which should have everything fixed now: https://github.com/adworacz/zsmooth/releases/tag/0.3

**Comment by Selur** [comment]
At least here it is not fixed, now I get a black bar on the right side,... (resolution: 720x480)
![grafik](https://github.com/adworacz/zsmooth/assets/843640/80d3fe31-3c50-4577-8456-1703e17eb066)

**Comment by adworacz** [comment]
Bugger okay, thank you for confirming.

I also found that it crashes with non 8-bit content as well, so I'll work on a new round of fixes.

**Comment by dnjulek** [comment]
>I also found that it crashes with non 8-bit content as well

For non 8-bit stride you need to divide it by @TypeOf(T)

**Comment by dnjulek** [comment]
If you don't want to divide, sekrit-twc usually casts the ptr back to u8 and always makes the ptr shift as u8.
example: 
https://github.com/vapoursynth/vapoursynth/blob/d27b54e121112cb85cdb8f4200c706396265bbb7/src/core/kernel/x86/convolution_avx2.cpp#L18-L21

**Comment by adworacz** [comment]
> > I also found that it crashes with non 8-bit content as well
> 
> For non 8-bit stride you need to divide it by `sizeOf(T)`

Yup, that's exactly the solution I came to myself. Since all divisions are powers of 2, I've got no problems using division since the compiler will optimize it all to right shifts anyways.

@Selur - I've got version 0.4 up now: https://github.com/adworacz/zsmooth/releases/tag/0.4

I tested it locally with TemporalMedian (radius = 1) on RGB, YUV420, YUV422, YUV444, in 1920x1080 and 720x480 and I get no black bars anywhere. I even added unit tests to assert the stride handling behavior.

So *fingers cross* all of the artifacts/black bars issues should be fixed now.

**Comment by Selur** [comment]
Doesn't work either.
![grafik](https://github.com/adworacz/zsmooth/assets/843640/721b8737-4d0c-49c5-8db0-fb1a5b39a37e)
(for both avx2 and avx512)

**Comment by Selur** [comment]
Just to show that it's not just mpeg2 content:
![grafik](https://github.com/adworacz/zsmooth/assets/843640/61b40711-f368-4e44-ae1b-ae854dcb1c42)
small sample (190x240, MPEG-4 ASP): [sample_mpeg4.zip](https://github.com/adworacz/zsmooth/files/15142274/sample_mpeg4.zip)

**Comment by dnjulek** [comment]
I've just build from source and the error doesn't happen, maybe the dll is wrong?

**Comment by Selur** [comment]
I tested both and used:
https://github.com/adworacz/zsmooth/releases/download/0.4/zsmooth.avx2.dll
https://github.com/adworacz/zsmooth/releases/download/0.4/zsmooth.avx512.dll
just tested it again.
![broken](https://github.com/adworacz/zsmooth/assets/843640/d6a9f92d-56dc-4720-a90a-c3fe6fa0b534)

**Comment by Selur** [comment]
To be sure it's nothing else I did, I simplified the script:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
core = vs.core
# loading plugins
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/LSMASHSource.dll")
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/DenoiseFilter/ZSmooth/zsmooth.avx2.dll")

# Source: 'C:\Users\Selur\Desktop\sample_mpeg4.mp4'
# Current color space: YUV420P8, bit depth: 8, resolution: 190x240, frame rate: 30fps, scanorder: progressive, yuv luminance scale: full, matrix: 470bg, transfer: bt.601
# Loading C:\Users\Selur\Desktop\sample_mpeg4.mp4 using LibavSMASHSource
clip = core.lsmas.LibavSMASHSource(source="C:/Users/Selur/Desktop/sample_mpeg4.mp4")

original = clip
clip = core.zsmooth.TemporalMedian(clip, radius=1)


original = core.text.Text(clip=original,text="Original",scale=1,alignment=7)
clip = core.text.Text(clip=clip,text="Filtered",scale=1,alignment=7)
stacked = core.std.StackHorizontal([original,clip])


# output
stacked.set_output()
```
![broken](https://github.com/adworacz/zsmooth/assets/843640/6fa89c0e-0e1c-4f57-8e1f-f921665180a0)

**Comment by Selur** [comment]
Okay, so it must be something related to my setup.
You did use https://github.com/adworacz/zsmooth/releases/download/0.4/zsmooth.avx2.dll right?

**Comment by dnjulek** [comment]
Yes, CRC64: E3D6E45A3C709BF6

**Comment by Selur** [comment]
Do you know a tool which calculates CRC64 on Windows?
```
SHA512-Hash of zsmooth.avx2.dll:
2c19f8cdce4b53be14d273b6bc20fb74263108d3fe5545c0c09a7f91c6fa2568b5a91b6178dd9a450c7013ad1e813ea57a0ac80697cf7e8537340408d1d9d6b0
```

**Comment by Selur** [comment]
found one:
crc64 zsmooth.avx2.dll
CRC: [0x50F2D3E114F1F9A4] File: [zsmooth.avx2.dll]

**Comment by Selur** [comment]
Redownloaded `https://github.com/adworacz/zsmooth/releases/download/0.4/zsmooth.avx2.dll`
crc64 is still `50F2D3E114F1F9A4`
Seems like we are using different files

**Comment by adworacz** [comment]
This is what I have on my end, which seems to match your original sha512, Selur

sha256
e6d9360b2fd8a1bc3a94ed81efd272bd533f6f553de9ef56a4d45a913ab8f7c3  zsmooth.avx2.dll

sha512
2c19f8cdce4b53be14d273b6bc20fb74263108d3fe5545c0c09a7f91c6fa2568b5a91b6178dd9a450c7013ad1e813ea57a0ac80697cf7e8537340408d1d9d6b0  zsmooth.avx2.dll

**Comment by adworacz** [comment]
I'll try testing with your sample

**Comment by adworacz** [comment]
Hmmm, I'm also seeing no issues at all using your test sample.

I'm using version 66 of Vapoursynth - what version are you using?

![no-artifacts](https://github.com/adworacz/zsmooth/assets/561689/da32a756-69e0-4721-b0cf-23fd37ee5b1b)

Used script:

```py
import vapoursynth as vs
core = vs.core

clip = core.lsmas.LibavSMASHSource("/home/adub/Downloads/sample_mpeg4.mp4")
zsmooth = clip.zsmooth.TemporalMedian(radius=1)

clip = clip.text.Text("Original")
zsmooth = zsmooth.text.Text("Filtered")
stacked = core.std.StackHorizontal([clip,zsmooth])
stacked.set_output(0)
```

**Comment by dnjulek** [comment]
>Do you know a tool which calculates CRC64 on Windows?

7-zip, right-click -> 7-zip has all the options.

**Comment by Selur** [comment]
I'm using R65 since some of the torch stuff I use isn't available for Python 3.12.
I'll test with R66.

**Comment by Selur** [comment]
> > Do you know a tool which calculates CRC64 on Windows?
> 
> 7-zip, right-click -> 7-zip has all the options.

Name: zsmooth.avx2.dll
Größe: 946176 Bytes (924 KiB)
CRC64: E3D6E45A3C709BF6
so we are using the same file :)

**Comment by Selur** [comment]
Using R66 I still have the same error. :(

**Comment by adworacz** [comment]
This is very strange. It's almost like the it's not processing all planes, or getting the wrong width for different planes.

I think I'm going to have to put a debug build together that spits out some of this information so we can see what the plugin is working with. I have no idea why it would be any different on your machine, since it should be using the same function calls in Vapoursynth for all of them.

It *is* interesting that the output looks a little different in VS 66 - there's some of the original image that's come through, but it's like one of the planes wasn't operated on properly.

**Comment by Selur** [comment]
> It is interesting that the output looks a little different in VS 66 - there's some of the original image that's come through, but it's like one of the planes wasn't operated on properly.
I agree, using the same script:
R65:
![grafik](https://github.com/adworacz/zsmooth/assets/843640/e4069743-3dc0-4508-8e85-c50d21756548)
R66:
![grafik](https://github.com/adworacz/zsmooth/assets/843640/a2804c16-294d-407a-b474-e9ef4254c491)

**Comment by NSQY** [comment]
I can reproduce this with the 0.4 release DLLs (both avx2 and avx512), however I cannot repo when compiling af9c95659b34d033dd8ae2172120282c0d217d83 with 0.13.0-dev.46+3648d7df1

Here's my env

Windows 11
7950X3D

```Copyright (c) 2012-2023 Fredrik Mellbin
        Core R66
        API R4.1
        API R3.6
        Options: -
        Number of Threads: 32
        Max Cache Size: 4096
```


Minimal test case:

```py
import vapoursynth as vs
core = vs.core

clip = core.std.BlankClip(None, width=720, height=480, format=vs.RGB24, color=[127]*3)

zsmooth = core.zsmooth.TemporalMedian(clip, radius=1)

zsmooth.set_output()
```

**Comment by adworacz** [comment]
Oh realllyyy???

That’s fascinating. I wonder if it’s a zig version difference (I’m using 0.12), or something else. 

Or are you saying that the issue was created in DLL 0.4?

@NSQY - would you mind trying a rebuild using  0.12 with the latest commit?

I want to track down if it’s a zig version thing or a bug introduced in 0.4.

**Comment by adworacz** [comment]
It might also be a cross-compilation issue, since I’m compiling the binaries on a Linux machine. Zig should be doing everything right for cross-compilation, but we’ll have to see. 

I’ll look into setting up a Windows VM so I can attempt to replicate the problem myself.

**Comment by NSQY** [comment]
>Or are you saying that the issue was created in DLL 0.4?

I'm saying that I can only reproduce with whatever was used to compile the provided .dll files, so either they're based off a different commit or something went wrong in the compile.

I can reproduce the original problem with ``git checkout 0.2``, but not the broken row of pixels. I can only reproduce this with the provided DLL. See the provided .webm.

[test512.webm](https://github.com/adworacz/zsmooth/assets/34185288/48fb622c-1176-4f8a-b102-89029b2c219e)

**Comment by NSQY** [comment]
992421d08eca6a5692beab08bd56d9818598d255

0.13.0-dev.46+3648d7df1 OK
0.12.0 OK

**Comment by NSQY** [comment]
I wrote a basic script that just checks the PlaneStatsAverage of all BlankClip frames and ensures they're all the same.

``..\zig-windows-x86_64-0.12.0\zig.exe build -Doptimize=ReleaseFast``
```
Test passed at commit 992421d08eca6a5692beab08bd56d9818598d255
Test passed at commit 2c36c478cfd0011c5739ee8a212a036fc93c69b6
Test passed at commit 690726fcb3a2df6142e6d24658a758250b833b40
Test passed at commit fb036ca4a4da4c403c055ca7eb06dad98a9d3073
Test passed at commit df86a2f6b83862a6720a05e65445b887dfe8c054
Test passed at commit cd1b7bae0ea7ebf4d50cce85a237e96fa1f19de6
Test passed at commit af9c95659b34d033dd8ae2172120282c0d217d83
Test passed at commit 8f5472849952ab1f59adaf01a7f83dc86dfec23f
Test passed at commit 156ec629543dc6575a474028d2178eba89dd71de
Test passed at commit 9e4457d577894d78af58fd765c96096aa677c46c
Test passed at commit 640ff1c4e20bc2c75e6dfd558047301e4b8293b1
Test passed at commit 5d40effeb758236e98b6dcf62a1c0931a7566951
Test failed at commit bb062280882a67603821fced5aa07a3cb2b84ec8: ERROR
Test failed at commit 3568626264eb04729df5f38eb11650b2cc0aa0e8: ERROR
Test failed at commit c4148f94d67e572d0c1fe068afafb8cb038aff3e: ERROR
Test failed at commit f303a18bc8825576288ec9d6f60c52da3c509f2c: ERROR
Test failed at commit 6137ada151550da02f24798cf45afb776b771d14: ERROR
Test failed at commit 7ce83e6089089e8104e4cd24bede54cf26f43edd: ERROR
Test failed at commit 6eed4ff6d87ca96518b180baecf26e100d7da4ca: ERROR
Test failed at commit fdb20191afc9e920a60b26a19e92ee1183ea1391: ERROR
Test failed at commit bdbe528db77d85a18a26ac5e728c221348417bf5: ERROR
Test failed at commit 21776f36345d5e0c9cf3ae75f564338f9033bd51: ERROR
```

**Comment by adworacz** [comment]
Okay, this is super helpful testing. 

The DLLs were compiled with this script, and cross compilation happens at this line specifically: 
https://github.com/adworacz/zsmooth/blob/992421d08eca6a5692beab08bd56d9818598d255/build_all_libs.sh#L6

This was done on my Intel laptop, running Linux. 

I’m going to set up a VM to see if I can get this issue reproduced. 

Meanwhile, it sounds like the workaround is simply for Windows users to compile their own DLLs from source on the machines they’re going to run the DLL on.

**Comment by NSQY** [comment]
I will try cross-compiling from my WSL AUR image. zig-windows-x86_64-0.13.0-dev.46+3648d7df1 errors at the same spot btw

```
Test passed at commit 992421d08eca6a5692beab08bd56d9818598d255
Test passed at commit 2c36c478cfd0011c5739ee8a212a036fc93c69b6
Test passed at commit 690726fcb3a2df6142e6d24658a758250b833b40
Test passed at commit fb036ca4a4da4c403c055ca7eb06dad98a9d3073
Test passed at commit df86a2f6b83862a6720a05e65445b887dfe8c054
Test passed at commit cd1b7bae0ea7ebf4d50cce85a237e96fa1f19de6
Test passed at commit af9c95659b34d033dd8ae2172120282c0d217d83
Test passed at commit 8f5472849952ab1f59adaf01a7f83dc86dfec23f
Test passed at commit 156ec629543dc6575a474028d2178eba89dd71de
Test passed at commit 9e4457d577894d78af58fd765c96096aa677c46c
Test passed at commit 640ff1c4e20bc2c75e6dfd558047301e4b8293b1
Test passed at commit 5d40effeb758236e98b6dcf62a1c0931a7566951
Test failed at commit bb062280882a67603821fced5aa07a3cb2b84ec8: ERROR
Test failed at commit 3568626264eb04729df5f38eb11650b2cc0aa0e8: ERROR
Test failed at commit c4148f94d67e572d0c1fe068afafb8cb038aff3e: ERROR
Test failed at commit f303a18bc8825576288ec9d6f60c52da3c509f2c: ERROR
Test failed at commit 6137ada151550da02f24798cf45afb776b771d14: ERROR
Test failed at commit 7ce83e6089089e8104e4cd24bede54cf26f43edd: ERROR
Test failed at commit 6eed4ff6d87ca96518b180baecf26e100d7da4ca: ERROR
```

>Meanwhile, it sounds like the workaround is simply for Windows users to compile their own DLLs from source on the machines they’re going to run the DLL on.

Thankfully zig makes this trivial 😊

**Comment by NSQY** [comment]
992421d08eca6a5692beab08bd56d9818598d255 .dll built with ``0.12.0`` on Arch using ``zig/zig build -Doptimize=ReleaseFast -Dtarget=x
86_64-windows -Dcpu=x86_64_v3`` is bad.

**Comment by adworacz** [comment]
This is great @NSQY ! I was starting to wonder the same thing, if it's related to the `-Dcpu` param.

If you run `zig build -Doptimize=ReleaseFast -Dcpu=x86_64_v3` on you **Windows** install (not cross-compiling from an OS level, but from a CPU level), does the issue reproduce?

I'm starting to suspect that there's something wrong with the chosen SIMD vector lengths, and I'm wondering if it's specific to the CPU and not the operating system. Both you and Selur are running 7950X's, which have AVX512 and would use a 64 element wide SIMD vector for 8-bit content (for 512 bits). *BUT* the `x86_64_v3` target uses a 32-element wide vector (256 bits), and shockingly [so does the `x86_64_v4` target](https://github.com/ziglang/zig/blob/master/lib/std/Target/x86.zig#L3923) 

In theory, this shouldn't matter, but maybe I have a bug in my math somewhere or for some reason running 256bit vectors on a machine that supports 512bit vectors may be causing some kind of issue.

**Comment by NSQY** [comment]
``build -Doptimize=ReleaseFast -Dcpu=x86_64_v3`` does indeed reproduce the ERROR with both zig ``0.12.0`` and ``0.13.0-dev.46+3648d7df1`` when compiled on Windows.

**Comment by adworacz** [comment]
Excellent, we’re really narrowing things down now. I have a suspicion on the source of the issue. 

I’ll try and get a potential fix together tonight.

**Comment by dnjulek** [comment]
I was checking this part of the code just now, I thought it would be here too.
About the width_simd formula, wouldn't  ``width - (width % vec_size)`` be better?

**Comment by adworacz** [comment]
> I was checking this part of the code just now, I thought it would be here too. About the width_simd formula, wouldn't `width - (width % vec_size)` be better?

They produce the exact same code after compilation. See this Compiler Explorer (Godbolt) link with both implementations. One jumps to other because they are identical.

https://zig.godbolt.org/z/fvW73PGrG

**Comment by adworacz** [comment]
Okay, I've committed potential fixes to Temporal Soften and FluxSmooth as well.

sha256
```
30fc26acad1c5e1708598ca1503e41f447280bd1703b7c70fb44c7ee4df07a5b  zsmooth.avx2.dll
```

Please try this version of the DLL:
[zsmooth.avx2.dll.zip](https://github.com/adworacz/zsmooth/files/15157414/zsmooth.avx2.dll.zip)

**Comment by Selur** [comment]
That one seems to work for me. 👍

**Comment by NSQY** [comment]
I think with this we're good to go.

https://github.com/adworacz/zsmooth/commit/992421d08eca6a5692beab08bd56d9818598d255 ``..\zig-windows-x86_64-0.12.0\zig.exe build -Doptimize=ReleaseFast -Dcpu=x86_64_v4``
<details>
 <summary>Summary</summary>

```
TemporalSoften1: ERROR
TemporalSoften2: ERROR
TemporalSoften3: ERROR
TemporalSoften4: ERROR
TemporalSoften5: ERROR
TemporalSoften6: ERROR
TemporalSoften7: ERROR
TemporalMedian1: ERROR
TemporalMedian2: ERROR
TemporalMedian3: ERROR
TemporalMedian4: ERROR
TemporalMedian5: ERROR
TemporalMedian6: ERROR
TemporalMedian7: ERROR
FluxSmoothT: ERROR
FluxSmoothST: OK
RemoveGrain1: OK
RemoveGrain2: OK
RemoveGrain3: OK
RemoveGrain4: OK
RemoveGrain5: OK
RemoveGrain6: OK
RemoveGrain7: OK
RemoveGrain8: OK
RemoveGrain9: OK
RemoveGrain10: OK
RemoveGrain11: OK
RemoveGrain12: OK
RemoveGrain13: OK
RemoveGrain14: OK
RemoveGrain15: OK
RemoveGrain16: OK
RemoveGrain17: OK
RemoveGrain18: OK
RemoveGrain19: OK
RemoveGrain20: OK
RemoveGrain21: OK
RemoveGrain22: OK
RemoveGrain23: OK
RemoveGrain24: OK
```
</details>

30fc26acad1c5e1708598ca1503e41f447280bd1703b7c70fb44c7ee4df07a5b  zsmooth.avx2.dll

<details>
 <summary>Summary</summary>

```
TemporalSoften1: OK
TemporalSoften2: OK
TemporalSoften3: OK
TemporalSoften4: OK
TemporalSoften5: OK
TemporalSoften6: OK
TemporalSoften7: OK
TemporalMedian1: OK
TemporalMedian2: OK
TemporalMedian3: OK
TemporalMedian4: OK
TemporalMedian5: OK
TemporalMedian6: OK
TemporalMedian7: OK
FluxSmoothT: OK
FluxSmoothST: OK
RemoveGrain1: OK
RemoveGrain2: OK
RemoveGrain3: OK
RemoveGrain4: OK
RemoveGrain5: OK
RemoveGrain6: OK
RemoveGrain7: OK
RemoveGrain8: OK
RemoveGrain9: OK
RemoveGrain10: OK
RemoveGrain11: OK
RemoveGrain12: OK
RemoveGrain13: OK
RemoveGrain14: OK
RemoveGrain15: OK
RemoveGrain16: OK
RemoveGrain17: OK
RemoveGrain18: OK
RemoveGrain19: OK
RemoveGrain20: OK
RemoveGrain21: OK
RemoveGrain22: OK
RemoveGrain23: OK
RemoveGrain24: OK
```
</details>


626ade0f90768bd27f8df0cc02454d7b28b95b48 ..\zig-windows-x86_64-0.12.0\zig.exe build -Doptimize=ReleaseFast -Dcpu=x86_64_v3

<details>
 <summary>Summary</summary>

```TemporalSoften1: OK
TemporalSoften2: OK
TemporalSoften3: OK
TemporalSoften4: OK
TemporalSoften5: OK
TemporalSoften6: OK
TemporalSoften7: OK
TemporalMedian1: OK
TemporalMedian2: OK
TemporalMedian3: OK
TemporalMedian4: OK
TemporalMedian5: OK
TemporalMedian6: OK
TemporalMedian7: OK
FluxSmoothT: OK
FluxSmoothST: OK
RemoveGrain1: OK
RemoveGrain2: OK
RemoveGrain3: OK
RemoveGrain4: OK
RemoveGrain5: OK
RemoveGrain6: OK
RemoveGrain7: OK
RemoveGrain8: OK
RemoveGrain9: OK
RemoveGrain10: OK
RemoveGrain11: OK
RemoveGrain12: OK
RemoveGrain13: OK
RemoveGrain14: OK
RemoveGrain15: OK
RemoveGrain16: OK
RemoveGrain17: OK
RemoveGrain18: OK
RemoveGrain19: OK
RemoveGrain20: OK
RemoveGrain21: OK
RemoveGrain22: OK
RemoveGrain23: OK
RemoveGrain24: OK
```
</details>

**Comment by dnjulek** [comment]
@Selur can you do this stride test? https://gist.github.com/dnjulek/3bdff6ac5893da6d6a1ba11d70bd0e67

Because vsapi should return mod64 stride for CPU with avx512 (already tested on a 7950x3d with correct result):
https://github.com/vapoursynth/vapoursynth/blob/58509e8dfa570f6fe8b8a8c6072e950efb02db23/src/core/vscore.cpp#L2408-L2416

**Comment by Selur** [comment]
Compiled the test and called it a few times:
```
F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.05 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (337.45 fps)

F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.00 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (604.30 fps)

F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.00 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (587.34 fps)

F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.00 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (527.73 fps)

F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.00 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (529.86 fps)

F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.00 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (578.10 fps)

F:\Hybrid\64bit\Vapoursynth>VSPipe.exe -p c:\Users\Selur\Desktop\test.vpy . -o 1
Script evaluation done in 0.00 seconds
Stride: 768
Stride mod32: 0
Stride mod64: 0
Output 1 frames in 0.00 seconds (634.96 fps)
```
(Windows 11, Ryzen 9 7950X)

**Comment by dnjulek** [comment]
Thanks, I'm going to do more tests to figure out these issues, because if the vector_size was 32 or 64 it couldn't be a problem with a mod64 stride.

**Comment by Selur** [comment]
No problem, if you need me to do some additional tests here to help, let me know.
